bool taskk1(int y);
bool taskk2(int p, int q) ;
bool taskk3(int n, int k);
bool taskk4(int x, int y, int z);
bool taskk5(int a, int b);
bool taskk6(int a, int b);
bool taskk7(int a, int b, int c);
bool taskk8(int a, int b, int c);
bool taskk9(int a, int b, int c);
bool taskk10(int a, int b, int c);
bool taskk11(int a, int b, int c);
bool taskk12(int a, int b, int c);